language: minimal
  
services:
  - docker

os: linux

env:
  global:
    - TRAVIS_COMMIT_SHORT=$(echo $TRAVIS_COMMIT | cut -c-7)
    - IMAGE_NAME=garage-door-rest-server
    - REPO_NAME=jnk5y/$IMAGE_NAME:latest
    - TARGET_PLATFORMS=linux/amd64,linux/arm/v7,linux/arm/v6,linux/arm64
  
install:
  - docker container run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker container run -d --rm --name buildkitd --privileged moby/buildkit:latest
  - sudo docker container cp buildkitd:/usr/bin/buildctl /usr/local/bin/
  - export BUILDKIT_HOST="docker-container://buildkitd"
  
script:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  - >
    buildctl build
    --progress=plain
    --frontend=dockerfile.v0
    --local context=.
    --local dockerfile=.
    --opt filename=Dockerfile
    --opt platform=$TARGET_PLATFORMS
    --opt build-arg:VCS_REF=$TRAVIS_COMMIT_SHORT
    --opt build-arg:BUILD_DATE=$(date -u +"%Y-%m-%dT%TZ")
    --output type=image,name=$REPO_NAME,push=true
