language: minimal
  
services:
  - docker

arch:
  - amd64
  - arm64
  - arm32

os: linux

env:
  global:
    - TRAVIS_COMMIT_SHORT=$(echo $TRAVIS_COMMIT | cut -c-7)
    - IMAGE_NAME=garage-door-rest-server
    - REPO_NAME=jnk5y/$IMAGE_NAME:latest
    - TARGET_PLATFORMS=linux/amd64
  
before_install:
  - docker build -t jnk5y/$IMAGE_NAME:$TRAVIS_COMMIT_SHORT -t $REPO_NAME .
  #  - export VERSION=$(curl --silent "https://api.github.com/repos/aquasecurity/trivy/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
  #  - wget https://github.com/aquasecurity/trivy/releases/download/v${VERSION}/trivy_${VERSION}_Linux-64bit.tar.gz
  #  - tar zxvf trivy_${VERSION}_Linux-64bit.tar.gz
  
before_script:
  #  - ./trivy --exit-code 0 --severity HIGH --no-progress $REPO_NAME
  #  - ./trivy --exit-code 1 --severity CRITICAL --no-progress $REPO_NAME

script:  
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  - docker push jnk5y/$IMAGE_NAME:$TRAVIS_COMMIT_SHORT
  - docker push $REPO_NAME

cache:
  directories:
    - $HOME/.cache/trivy
