language: python

python:
  - 3.8
  
services:
  - docker
  
env:
  global:
    - TRAVIS_COMMIT_SHORT=$(echo $TRAVIS_COMMIT | cut -c-7)
    - IMAGE_NAME=garage-door-rest-server
    - REPO_NAME=jnk5y/$IMAGE_NAME:latest
    - TARGET_PLATFORMS=linux/amd64
  
before_install:
  - docker build -t jnk5y/$IMAGE_NAME:$TRAVIS_COMMIT_SHORT -t $REPO_NAME .
  
after_success:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  - docker push jnk5y/$IMAGE_NAME:$TRAVIS_COMMIT_SHORT
  - docker push $REPO_NAME
